name: todolist
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: ^0.9.2



flutter_native_splash:
  color: "#08606b"
  image: "./assets/splashscreen/icon.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./assets/splashscreen/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

